# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# pages statiques (ou presque)
homepage:
  url:   /
  param: { module: edt, action: index }

faq:
  url:   /faq
  param: { module: edt, action: faq }

# actions cron
cron:
  url:  /cron/:action/*
  param: { module: cron }

# actions notice. kSdsZhrS is the "password"
notice:
  url:  /kSdsZhrS/:action/:filiere/:promo/:semaine/*
  param: { module: notice }

# (re)set cookie
cookie_set:
  url:  /cookie/set/:filiere/:promo/:semaine/*
  param: { module: edt, action: set }

cookie_reset:
  url:  /cookie/reset/:filiere/:promo/:semaine/*
  param: { module: edt, action: reset }

# Image gif d'une semaine, puis celle par défaut
image_img:
  url:  /img/:filiere/:promo/:semaine/*
  param: { module: img, action: img }

image_img_default:
  url:  /img/:filiere/:promo/*
  param: { module: img, action: img }

# détails sur l'image d'une semaine
details_img:
  url:  /details/:filiere/:promo/:semaine/*
  param: { module: img, action: details }

# iCal update
ical_update:
  url:  /ical_update/:filiere/:promo/*
  param: { module: ical, action: update }

# iCal
ical:
  url:  /ical/:filiere/:promo/ical.ics
  param: { module: ical, action: ical }


# Page de l'edt pour la semaine courante
image_default_index:
  url:  /:filiere/:promo
  param: { module: edt, action: image }

# Page pour une semaine, puis pour la semaine par défaut
image:
  url:  /:filiere/:promo/:semaine
  param: { module: edt, action: image}

image_default:
  url:  /:filiere/:promo/*
  param: { module: edt, action: image }

# Page pour une filière
filiere_index:
  url:   /:filiere
  param: { module: edt, action: indexPromo }


# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
