# Configuration:
#   columns:
#     identifier:   { type: string(255) }
#     

Filiere:
  columns:
    url:     { type: string(255) }
    nom:     { type: string(255) }
    description:     { type: string(4000) }
    logo:    { type: string(255) }
  relations:
    Promotions:  { class: Promotion, local: id, foreign: filiere_id, type: many }

Promotion:
  columns:
    url:     { type: string(255) }
    nom:     { type: string(255) }
    description:        { type: string(4000) }
    filiere_id:         { type: integer, notnull: true }
    conf_trees:         { type: string(255) }
  relations:
    Filiere:  { local: filiere_id, foreign: id, type: one }

#     Pourra servir pour l'iCal
#     conf_branch_id:     { type: string(255) }
#     conf_select_branch_id: { type: string(255) }
#     conf_select_id:     { type: string(255) }