# Configuration:
#   columns:
#     identifier:   { type: string(255) }
#     project_id:         { type: string(255) }
#       'displayMode' => '1057855',
#       'displayConfId' => '8',

Filiere:
  columns:
    url:                { type: string(255) }
    nom:                { type: string(255) }
    description:        { type: string(4000) }
    logo:               { type: string(255) }
  relations:
    Promotions:  { class: Promotion, local: id, foreign: filiere_id, type: many }

Promotion:
  columns:
    url:                { type: string(255) }
    nom:                { type: string(255) }
    description:        { type: string(4000) }
    filiere_id:         { type: integer, notnull: true }
    id_tree:            { type: string(255) }
    branch_id:          { type: string(255) }
    select_branch_id:   { type: string(255) }
    select_id:          { type: string(255) }
    id_piano_day:       { type: string(255), default: '0,1,2,3,4' }
    width:              { type: integer, default: 800 }
    height:             { type: integer, default: 600 }
  relations:
    Filiere:  { local: filiere_id, foreign: id, type: one }
